//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.10 at 01:59:36 PM EEST 
//


package com.fawry.crud.bkregistration;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.fawry.crud.bkregistration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.fawry.crud.bkregistration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetRegistrationByIdRequest }
     * 
     */
    public GetRegistrationByIdRequest createGetRegistrationByIdRequest() {
        return new GetRegistrationByIdRequest();
    }

    /**
     * Create an instance of {@link GetRegistrationByIdResponse }
     * 
     */
    public GetRegistrationByIdResponse createGetRegistrationByIdResponse() {
        return new GetRegistrationByIdResponse();
    }

    /**
     * Create an instance of {@link BKRegistrationResRead }
     * 
     */
    public BKRegistrationResRead createBKRegistrationResRead() {
        return new BKRegistrationResRead();
    }

    /**
     * Create an instance of {@link GetRegistrationsResponse }
     * 
     */
    public GetRegistrationsResponse createGetRegistrationsResponse() {
        return new GetRegistrationsResponse();
    }

    /**
     * Create an instance of {@link GetRegistrationsRequest }
     * 
     */
    public GetRegistrationsRequest createGetRegistrationsRequest() {
        return new GetRegistrationsRequest();
    }

    /**
     * Create an instance of {@link DeleteByIdRequest }
     * 
     */
    public DeleteByIdRequest createDeleteByIdRequest() {
        return new DeleteByIdRequest();
    }

    /**
     * Create an instance of {@link DeleteByIdResponse }
     * 
     */
    public DeleteByIdResponse createDeleteByIdResponse() {
        return new DeleteByIdResponse();
    }

    /**
     * Create an instance of {@link CreateBKRegistrationRequest }
     * 
     */
    public CreateBKRegistrationRequest createCreateBKRegistrationRequest() {
        return new CreateBKRegistrationRequest();
    }

    /**
     * Create an instance of {@link CreateRegistrationResponse }
     * 
     */
    public CreateRegistrationResponse createCreateRegistrationResponse() {
        return new CreateRegistrationResponse();
    }

    /**
     * Create an instance of {@link UpdateBKRegistrationRequest }
     * 
     */
    public UpdateBKRegistrationRequest createUpdateBKRegistrationRequest() {
        return new UpdateBKRegistrationRequest();
    }

    /**
     * Create an instance of {@link UpdateRegistrationResponse }
     * 
     */
    public UpdateRegistrationResponse createUpdateRegistrationResponse() {
        return new UpdateRegistrationResponse();
    }

    /**
     * Create an instance of {@link BKRegistrationResReadUpdate }
     * 
     */
    public BKRegistrationResReadUpdate createBKRegistrationResReadUpdate() {
        return new BKRegistrationResReadUpdate();
    }

    /**
     * Create an instance of {@link CustomerResRead }
     * 
     */
    public CustomerResRead createCustomerResRead() {
        return new CustomerResRead();
    }

}
