//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.09.10 at 01:59:36 PM EEST 
//


package com.fawry.crud.bkregistration;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BKRegistrationResReadUpdate" type="{http://fawry.com/crud/bkregistration}BKRegistrationResReadUpdate"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bkRegistrationResReadUpdate"
})
@XmlRootElement(name = "UpdateRegistrationResponse")
public class UpdateRegistrationResponse {

    @XmlElement(name = "BKRegistrationResReadUpdate", required = true)
    protected BKRegistrationResReadUpdate bkRegistrationResReadUpdate;

    /**
     * Gets the value of the bkRegistrationResReadUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link BKRegistrationResReadUpdate }
     *     
     */
    public BKRegistrationResReadUpdate getBKRegistrationResReadUpdate() {
        return bkRegistrationResReadUpdate;
    }

    /**
     * Sets the value of the bkRegistrationResReadUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BKRegistrationResReadUpdate }
     *     
     */
    public void setBKRegistrationResReadUpdate(BKRegistrationResReadUpdate value) {
        this.bkRegistrationResReadUpdate = value;
    }

}
