spring.application.name=crud
spring.datasource.ebppconfiguration.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.ebppcore.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.ebppcore.url=jdbc:oracle:thin:@localhost:1522:orcl
spring.dataSource.ebppcore.username=EBPP_CORE
spring.datasource.ebppcore.password=EBPP_CORE

spring.datasource.ebppconfiguration.url=jdbc:oracle:thin:@localhost:1522:orcl
spring.dataSource.ebppconfiguration.username=EBPP_CONFIGURATION
spring.datasource.ebppconfiguration.password=EBPP_CONFIGURATION


spring.main.allow-bean-definition-overriding=true

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=trace
#spring.jpa.hibernate.ddl-auto=update

server.port=8081

#server.servlet.context-path=/api/v1/

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
